apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prod-mq-qm01-instance
  annotations:
    argocd.argoproj.io/sync-wave: "300"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: prod
    server: https://kubernetes.default.svc
  project: applications
  source:
    path: mq/environments/prod/mq-qm01/
    repoURL: https://github.com/sepe/multi-tenancy-gitops-apps.git
    targetRevision: master
  syncPolicy: {}
