apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: eci-ace-jenkins
  annotations:
    argocd.argoproj.io/sync-wave: "300"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: ace-jenkins
    server: https://kubernetes.default.svc
  project: applications
  source:
    path: eci/environments/ace-jenkins
    repoURL: https://github.com/sepe/multi-tenancy-gitops-apps.git
    targetRevision: master
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
